import type { CheckGroupOption } from '@/components/rhfInputs/RHFCheckGroup';
import type { RadioGroupOption } from '@/components/rhfInputs/RHFRadioGroup';
import type { AutoCompleteOption } from '@/components/rhfInputs/RHFSelect';
import type { SwitchGroupOption } from '@/components/rhfInputs/RHFSwitchGroup';
import type { CommonTagInputItem } from '@/components/rhfInputs/RHFTagInput';
import type { ToggledOption } from '@/components/rhfInputs/RHFToggle';
import type { CommonFormProps } from '@/types';
import type { Moment } from 'moment';
export type FormValues = {
  TextField: string | null;
  SelectField: AutoCompleteOption | null;
  SelectMultiField: AutoCompleteOption[] | null;
  RadioField: boolean | null;
  CheckField: boolean | null;
  SwitchField: boolean | null;
  SelectBooleanField: boolean | null;
  DateField: Moment | null;
  DateTimeField: Moment | null;
  Place: AutoCompleteOption[] | null;
  Places: AutoCompleteOption[] | null;
  TimeField: Moment | null;
  DateMultiField: Moment[] | null;
  DateMultiField2: Moment[] | null;
  DateMultiField3: Moment[] | null;
  CheckGroupField: CheckGroupOption[] | null;
  RadioGroupField: RadioGroupOption[] | null;
  SwithGroupField: SwitchGroupOption[] | null;
  TagInputField: CommonTagInputItem[] | null;
  NumberField: number | null;
  Toggle: ToggledOption | null;
  Toggle2: ToggledOption[] | null;
};
export type FormProps = CommonFormProps<FormValues>;
export type FormComponent = ComponentType<FormProps>;
export type FileData = {
  id?: string;
  file?: File;
  source?: string;
};
