export type DocumnentIncomming = {};
export type OfficerType = 'CANBO' | 'DONVI';
export type Officer = {
  CanBoId?: string | null;
  CapDonVi?: number | null;
  ChuTri?: boolean | null;
  ChucVu?: string | null;
  ChucVuCustom?: string | null;
  ChucVuId?: string | null;
  Deep?: number | null;
  DonViId?: string | null;
  DuongDan_ID_DonVi?: string | null;
  DuongDan_ID_DonVi_Cha?: string | null;
  HasChild?: boolean | null;
  Id?: string | null;
  IdInt?: number | null;
  IsCaNhan?: boolean | null;
  IsCoVanThu?: boolean | null;
  IsDaPhanXL?: boolean | null;
  IsDelete?: boolean | null;
  IsDonVi?: boolean | null;
  IsEdit?: boolean | null;
  IsEditChuTri?: boolean | null;
  IsEditNhanDeBiet?: boolean | null;
  IsEditPhoiHop?: boolean | null;
  IsEditVanBanGiay?: boolean | null;
  IsLanhDaoNhanBaoCao?: boolean | null;
  IsOld?: boolean | null;
  IsVanThu?: boolean | null;
  IsVirtualDepartment?: boolean | null;
  LanhDao?: boolean | null;
  NhanDeBiet?: boolean | null;
  OwnerTypeId?: string | null;
  OwnerTypeName?: string | null;
  ParentId?: string | null;
  ParentIdInt?: number | null;
  PhamViNguoiTaoId?: string | null;
  PhanXuLyChaId?: string | null;
  PhanXuLyId?: string | null;
  PhoiHop?: boolean | null;
  TaskId?: string | null;
  Ten?: string | null;
  TenCustom?: string | null;
  TenDonVi?: string | null;
  TenDonViKhongDau?: string | null;
  TenKhongDau?: string | null;
  TenTaiKhoan?: string | null;
  ThuTu?: number | null;
  Type?: OfficerType;
  VanBanGiay?: boolean | null;
  XuLyNhiemVuId?: string | null;
  isCellExpanded?: boolean | null;
};
export type DocumentProcessStep = {
  StepName: string;
  DocumentStatus: string;
  NextSteps?: DocumentProcessStep[];
  PreviousSteps?: DocumentProcessStep[];
};
